"""Business objective: keep business logic portable across databases, models, and document technologies.

Technical description: declares Protocol-based ports consumed by the application layer, including Decimal-safe review accounting and bounded model extraction.
"""

from __future__ import annotations

from decimal import Decimal
from pathlib import Path
from typing import Protocol, Sequence

from invoice_canonicalizer.domain.models import (
    AliasRecord,
    CanonicalProduct,
    CanonicalizationDecision,
    ExtractionProviderResult,
    InvoiceLine,
    ParsedDocument,
    ProviderResult,
    ReviewRecord,
    StoredInvoiceLine,
    ReviewStatus,
)


class CatalogRepository(Protocol):
    def initialize(self) -> None: ...
    def seed_from_file(self, path: Path) -> None: ...
    def save_invoice_document(self, parsed: ParsedDocument, tenant_id: str, partner_id: str) -> None: ...
    def link_invoice_decision(self, tenant_id: str, document_id: str, source_line_id: str, decision: CanonicalizationDecision) -> None: ...
    def get_invoice_document(self, tenant_id: str, document_id: str) -> ParsedDocument | None: ...
    def get_invoice_line_records(self, tenant_id: str, document_id: str) -> Sequence[StoredInvoiceLine]: ...
    def find_approved_alias(self, tenant_id: str, partner_id: str, normalized_alias: str) -> AliasRecord | None: ...
    def list_aliases(self, tenant_id: str, partner_id: str) -> Sequence[tuple[AliasRecord, CanonicalProduct]]: ...
    def get_product(self, tenant_id: str, product_id: str) -> CanonicalProduct | None: ...
    def get_cached_decision(self, tenant_id: str, line_hash: str, taxonomy_version: str) -> CanonicalizationDecision | None: ...
    def save_decision(self, decision: CanonicalizationDecision, line_hash: str) -> None: ...
    def create_or_update_review(self, review: ReviewRecord) -> ReviewRecord: ...
    def update_pending_review(self, review: ReviewRecord) -> ReviewRecord: ...
    def find_pending_review_by_candidate_key(self, tenant_id: str, partner_id: str, candidate_key: str) -> ReviewRecord | None: ...
    def record_review_occurrence(
        self,
        tenant_id: str,
        review_id: str,
        source_description: str,
        source_line_id: str,
        affected_value: Decimal,
        currency: str | None,
    ) -> ReviewRecord: ...
    def list_reviews(
        self,
        tenant_id: str,
        status: ReviewStatus | None = ReviewStatus.PENDING,
        limit: int = 100,
        sort_by_priority: bool = True,
    ) -> Sequence[ReviewRecord]: ...
    def get_review(self, tenant_id: str, review_id: str) -> ReviewRecord | None: ...
    def approve_review(
        self,
        tenant_id: str,
        review_id: str,
        approved_description: str,
        target_product_id: str | None,
        approved_category: str | None = None,
    ) -> CanonicalProduct: ...
    def reject_review(self, tenant_id: str, review_id: str) -> ReviewRecord: ...
    def record_audit(self, tenant_id: str, event_type: str, payload: dict[str, object]) -> None: ...


class ModelProvider(Protocol):
    @property
    def name(self) -> str: ...

    @property
    def model(self) -> str: ...

    def estimate_cost(self, system_prompt: str, user_prompt: str, *, output_token_budget: int | None = None) -> Decimal: ...
    def generate_candidate(self, system_prompt: str, user_prompt: str) -> ProviderResult: ...
    def extract_invoice(self, system_prompt: str, user_prompt: str) -> ExtractionProviderResult: ...


class DocumentParser(Protocol):
    @property
    def extensions(self) -> tuple[str, ...]: ...

    @property
    def name(self) -> str: ...

    def parse(self, path: Path, tenant_id: str, partner_id: str) -> ParsedDocument: ...


class Canonicalizer(Protocol):
    def canonicalize(self, line: InvoiceLine, budget: "DocumentBudget | None" = None) -> CanonicalizationDecision: ...


class DocumentBudget(Protocol):
    def reserve_call(self, estimated_cost_usd: Decimal = Decimal("0")) -> None: ...
    def register_actual_cost(self, estimated_cost_usd: Decimal) -> None: ...
